---
name: Main

on: [push, pull_request]

jobs:
  go-tests:
    runs-on: self-hosted
    container:
      image: golang:1.17.11
      options: --user 1000
    if: github.repository == 'vocdoni/vocdoni-node'
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: debug go cache permissions
        run: |
          whoami || true
          ls -ld /github/ || true
          ls -ld /github/home/ || true
          ls -ld /github/home/.cache/ || true
          ls -ld /github/home/.cache/go-build/ || true
          find ~/.cache -not -user `id --user` -print0 | xargs -0 ls -ld || true
          find ~/.cache -user `id --user` -print0 | xargs -0 ls -ld || true
          epoch=$(date +%s)
          mv ~/.cache ~/.cache-broken-by-root-$epoch
          # cp -pr ~/.cache-broken-by-root-$epoch ~/.cache
          ls -ld ~/.cache*
          find ~/.cache -not -user `id --user` -print0 | xargs -0 ls -ld || true

  compose-test:
    runs-on: self-hosted
    if: github.repository == 'vocdoni/vocdoni-node'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

  docker-release:
    runs-on: self-hosted
    needs: [go-tests, compose-test]
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/stage' || startsWith(github.ref, 'refs/heads/release') || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/ethless'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      # - name: Set up QEMU
      #   id: qemu
      #   uses: docker/setup-qemu-action@v1
      #   with:
      #     image: tonistiigi/binfmt:latest
      #     platforms: all
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Get short branch name
        id: var
        shell: bash
        # Grab the short branch name, convert slashes to dashes
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-' )"
      - name: Push to Docker Hub, Packages and ghcr.io
        uses: docker/build-push-action@v2
        with:
          context: .
          # platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            vocdoni/go-dvote:latest, vocdoni/go-dvote:${{ steps.var.outputs.branch }},
            ghcr.io/vocdoni/go-dvote:latest,ghcr.io/vocdoni/go-dvote:${{ steps.var.outputs.branch }}

      - name: Push to Docker Hub, Packages and ghcr.io (race enabled)
        uses: docker/build-push-action@v2
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master'
        with:
          context: .
          push: true
          build-args: |
            BUILDARGS=-race
          tags: |
            vocdoni/go-dvote:latest-race, vocdoni/go-dvote:${{ steps.var.outputs.branch }}-race,
            ghcr.io/vocdoni/go-dvote:latest-race,ghcr.io/vocdoni/go-dvote:${{ steps.var.outputs.branch }}-race
